# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      
      - uses: actions/checkout@master

      - name: Trigger night mode
        run: |
          git config --local user.email github-actions@github.com
          git config --local user.name github-actions
          which sed
          cat $GITHUB_WORKSPACE/_sass/_base.scss
          /bin/sed -i 's/white/black/g' $GITHUB_WORKSPACE/_sass/_base.scss
          /bin/sed -i 's/black;/white;/g' $GITHUB_WORKSPACE/_sass/_base.scss
          git commit -m "Trigger night mode" -a
          git push
